### ISSUE TITLE
Question: Query height values

### ISSUE THREAD

**Issue by nihalkenkre** [UnrealXinda/FFTOcean#1]
Hello.

Given the current shader based approach, can the height values for a point on the xy plane be queried from the CPU.

Best regards.
Nihal

**Comment by UnrealXinda** [comment]
You could try this: https://docs.unrealengine.com/en-US/BlueprintAPI/Rendering/ReadRenderTargetPixel/index.html
Note that this is super inefficient. So don’t do this too much on every frame.

**Comment by nihalkenkre** [comment]
Aah.

great.. came across the render target approach on another video on buoyancy. cool..

thanks you.
